// Deterministic derivatives of the committed curated GLB; no network or renderer.
import { mkdir } from "node:fs/promises";
import { NodeIO } from "@gltf-transform/core";
import { KHRDracoMeshCompression } from "@gltf-transform/extensions";
import draco3d from "draco3dgltf";
import { Box3, PerspectiveCamera, Vector3 } from "three";
import { FOV, HOME_DIRECTION, homeDistance } from "@/lib/brain/framing";

type Point = [number, number];
type Segment = [Point, Point];
export const ART_VIEWBOX = "0 0 1000 1000";
export const ART_FILES = ["public/art/specimen-outline.svg", "public/art/coronal-section.svg"] as const;
const GRID = 720;
const CORONAL_Z = 0; // Metres, the same coronal plane as Slice at 0 mm.

type Projection = { camera: PerspectiveCamera; scale: number; depth: Float64Array; labels: Int16Array };

function rasterize([a, b, c]: number[][], { depth, labels }: Projection, label: number) {
  const denominator = (b[1] - c[1]) * (a[0] - c[0]) + (c[0] - b[0]) * (a[1] - c[1]);
  if (Math.abs(denominator) < 1e-8) return;
  for (let y = Math.max(0, Math.floor(Math.min(a[1], b[1], c[1]))); y <= Math.min(GRID - 1, Math.ceil(Math.max(a[1], b[1], c[1]))); y++) {
    for (let x = Math.max(0, Math.floor(Math.min(a[0], b[0], c[0]))); x <= Math.min(GRID - 1, Math.ceil(Math.max(a[0], b[0], c[0]))); x++) {
      const u = ((b[1] - c[1]) * (x + 0.5 - c[0]) + (c[0] - b[0]) * (y + 0.5 - c[1])) / denominator;
      const v = ((c[1] - a[1]) * (x + 0.5 - c[0]) + (a[0] - c[0]) * (y + 0.5 - c[1])) / denominator;
      if (u < 0 || v < 0 || u + v > 1) continue;
      const z = u * a[2] + v * b[2] + (1 - u - v) * c[2];
      const pixel = y * GRID + x;
      if (z < depth[pixel]) { depth[pixel] = z; labels[pixel] = label; }
    }
  }
}

/** Connect quantized endpoints, then remove sub-pixel triangle/raster detail. */
export function contours(segments: Segment[], tolerance: number): Point[][] {
  const key = (p: Point) => `${Math.round(p[0] * 1000)},${Math.round(p[1] * 1000)}`;
  const adjacent = new Map<string, number[]>();
  segments.forEach((segment, i) => segment.forEach((p) => {
    const k = key(p);
    const list = adjacent.get(k) ?? [];
    list.push(i);
    adjacent.set(k, list);
  }));
  const used = new Set<number>();
  const lines: Point[][] = [];
  const walk = (start: number, end: number) => {
    const line = [segments[start][end]];
    let current = start;
    let direction = end;
    while (!used.has(current)) {
      used.add(current);
      const next = segments[current][1 - direction];
      line.push(next);
      const candidate = adjacent.get(key(next))?.find((i) => !used.has(i));
      if (candidate === undefined) break;
      current = candidate;
      direction = key(segments[current][0]) === key(next) ? 0 : 1;
    }
    const simplified = simplify(line, tolerance);
    if (simplified.length > 1) lines.push(simplified);
  };
  // Open lines first; remaining edges form loops.
  segments.forEach((segment, i) => segment.forEach((p, end) => {
    if (!used.has(i) && adjacent.get(key(p))?.length === 1) walk(i, end);
  }));
  segments.forEach((_, i) => { if (!used.has(i)) walk(i, 0); });
  return lines;
}

function simplify(points: Point[], tolerance: number): Point[] {
  if (points.length <= 2) return points;
  const a = points[0], b = points.at(-1)!;
  const dx = b[0] - a[0], dy = b[1] - a[1];
  let furthest = 0, distance = tolerance * tolerance;
  for (let i = 1; i < points.length - 1; i++) {
    const p = points[i];
    const t = dx || dy ? Math.max(0, Math.min(1, ((p[0] - a[0]) * dx + (p[1] - a[1]) * dy) / (dx * dx + dy * dy))) : 0;
    const d = (p[0] - a[0] - t * dx) ** 2 + (p[1] - a[1] - t * dy) ** 2;
    if (d > distance) { distance = d; furthest = i; }
  }
  if (!furthest) return [a, b];
  return [...simplify(points.slice(0, furthest + 1), tolerance).slice(0, -1), ...simplify(points.slice(furthest), tolerance)];
}

export function intersectCoronal(triangle: Vector3[], z: number): Segment | null {
  const points: Point[] = [];
  for (let i = 0; i < 3; i++) {
    const a = triangle[i], b = triangle[(i + 1) % 3];
    if ((a.z <= z && b.z > z) || (b.z <= z && a.z > z)) {
      const t = (z - a.z) / (b.z - a.z);
      points.push([(a.x + t * (b.x - a.x)) * 4500 + 500, 500 - (a.y + t * (b.y - a.y)) * 4500]);
    }
  }
  return points.length === 2 ? [points[0], points[1]] : null;
}

const path = (lines: Point[][]) => lines.map((line) => line.map((p, i) => `${i ? "L" : "M"}${p[0].toFixed(1)} ${p[1].toFixed(1)}`).join("")).join("");
const svg = (body: string) => `<svg xmlns="http://www.w3.org/2000/svg" viewBox="${ART_VIEWBOX}" fill="none" stroke="var(--ink-soft, #5D5752)" stroke-width="1" stroke-linejoin="round" stroke-linecap="round"><metadata>Derived from Z-Anatomy / BodyParts3D, CC BY-SA 4.0. See /models/CREDITS.md. Generated by bun run build:brain-art.</metadata>${body}</svg>\n`;
const svgPath = (d: string, attributes = "") => `<path ${attributes} vector-effect="non-scaling-stroke" d="${d}"/>`;

async function main() {
  const io = new NodeIO().registerExtensions([KHRDracoMeshCompression])
    .registerDependencies({ "draco3d.decoder": await draco3d.createDecoderModule() });
  const doc = await io.read("public/models/brain.glb");
  const bounds = new Box3();
  const meshes = doc.getRoot().listNodes().map((node) => ({
    name: node.getName(), context: !!node.getExtras().context,
    primitives: node.getMesh()!.listPrimitives().map((primitive) => {
      const position = primitive.getAttribute("POSITION")!;
      const vertices = Array.from({ length: position.getCount() }, (_, i) => {
        const p = new Vector3().fromArray(position.getElement(i, [0, 0, 0]));
        bounds.expandByPoint(p);
        return p;
      });
      return { vertices, indices: primitive.getIndices()!.getArray()! };
    }),
  }));
  const size = bounds.getSize(new Vector3()).toArray() as [number, number, number];
  // SVG views share one asset. Portrait keeps the perspective of a phone's
  // backed-off home camera, rather than shrinking the desktop perspective.
  const projections: Projection[] = [2, 0.5].map((aspect) => {
    const distance = homeDistance(size, aspect);
    const camera = new PerspectiveCamera(FOV, 1, 0.02, 3);
    camera.position.set(...HOME_DIRECTION).setLength(distance);
    camera.lookAt(0, 0, 0);
    camera.updateMatrixWorld();
    return { camera, scale: distance / homeDistance(size, 2), depth: new Float64Array(GRID * GRID).fill(Infinity), labels: new Int16Array(GRID * GRID).fill(-1) };
  });
  const sections: string[] = [];
  let anchor: Point | undefined;

  meshes.forEach((mesh, label) => {
    if (mesh.context) return; // White matter is hidden in the home view.
    const intersections: Segment[] = [];
    for (const { vertices, indices } of mesh.primitives) {
      const projected = projections.map(({ camera, scale }) => vertices.map((v) => {
        const p = v.clone().project(camera);
        return [(p.x * scale + 1) * GRID / 2, (1 - p.y * scale) * GRID / 2, p.z];
      }));
      for (let i = 0; i < indices.length; i += 3) {
        const triangle = [vertices[indices[i]], vertices[indices[i + 1]], vertices[indices[i + 2]]];
        const section = intersectCoronal(triangle, CORONAL_Z);
        if (section) intersections.push(section);
        projections.forEach((projection, j) => rasterize([projected[j][indices[i]], projected[j][indices[i + 1]], projected[j][indices[i + 2]]], projection, label));
      }
    }
    const lines = contours(intersections, 0.7);
    if (lines.length) sections.push(svgPath(path(lines), `data-structure="${mesh.name}"`));
    if (mesh.name === "thalamus.l") {
      anchor = intersections.flat().sort((a, b) => b[0] - a[0])[0];
    }
  });

  const outlines = projections.map(({ labels }) => {
    const edges = new Map<string, Segment[]>();
    const add = (a: number, b: number, segment: Segment) => {
      if (a === b || (a < 0 && b < 0)) return;
      // Keep silhouettes and anatomical boundaries; omit tessellation edges.
      const key = a < 0 || b < 0 ? "silhouette" : [a, b].sort((x, y) => x - y).join(":");
      const list = edges.get(key) ?? [];
      list.push(segment);
      edges.set(key, list);
    };
    const point = (x: number, y: number): Point => [x * 1000 / GRID, y * 1000 / GRID];
    for (let y = 1; y < GRID; y++) for (let x = 1; x < GRID; x++) {
      const here = labels[y * GRID + x];
      add(here, labels[y * GRID + x - 1], [point(x, y), point(x, y + 1)]);
      add(here, labels[(y - 1) * GRID + x], [point(x, y), point(x + 1, y)]);
    }
    return [...edges.values()].map((segments) => svgPath(path(contours(segments, 1.3)))).join("");
  });
  const outline = `<view id="portrait" viewBox="1000 0 1000 1000"/><g>${outlines[0]}</g><g transform="translate(1000 0)">${outlines[1]}</g>`;
  if (!anchor) throw new Error("Coronal plane misses the Thalamus callout");
  const [x, y] = anchor;
  // SVG viewport units compensate for viewBox scaling: an 8px ring and an
  // 11px caption stay readable at both page widths, just like the 1px strokes.
  const calloutStyle = "<style>text{font-size:calc(11000px * 1px / 100vw);letter-spacing:calc(1200px * 1px / 100vw)}circle{r:calc(4000px * 1px / 100vw)}</style>";
  const callout = `${calloutStyle}${svgPath(`M${x.toFixed(1)} ${y.toFixed(1)}L790 250L970 250`)}<circle cx="${x.toFixed(1)}" cy="${y.toFixed(1)}" r="4" fill="var(--paper, #FCFBFA)" stroke="var(--oxblood, #6E1F24)" stroke-width="1.5" vector-effect="non-scaling-stroke"/><text x="790" y="232" fill="var(--ink-soft, #5D5752)" stroke="none" font-family="Geist Mono, monospace" font-size="32" letter-spacing="2.5">THALAMUS</text>`;
  await mkdir("public/art", { recursive: true });
  for (const [i, body] of [outline, sections.join("") + callout].entries()) {
    const output = svg(body);
    if (Buffer.byteLength(output) >= 30_000) throw new Error(`${ART_FILES[i]} exceeds 30 KB`);
    await Bun.write(ART_FILES[i], output);
    console.log(`${ART_FILES[i]}: ${Buffer.byteLength(output)} bytes`);
  }
  await Bun.write("lib/brain/art-framing.json", JSON.stringify({ widthHeightRatio: homeDistance(size, 1) / homeDistance(size, 2) }) + "\n");
}

if (import.meta.main) await main();
